export const PROJECT_NAME = "ProjectName"; //string
export const VISUALIZATION_OBJECT = "VisualizationObject"; //string
export const PROJECT_DATES = "ProjectDates"; //string
export const PROJECT_SQUARE = "ProjectSquare"; // number
export const PROJECT_RESOLUTION = "ProjectResolution"; //string
export const EXTRA_DESCRIPTION = "ExtraDescription"; //string
export const MODEL_3D = "Model3d"; //string
export const PROPERTY_CLASS = "PropertyClass"; //string
export const MAP_LINK = "MapLink"; //string
export const SEASON = "Season"; //string
export const HEIGHT_POINT_VIEW = "HeightPointView"; // number
export const NIGHT_POINT_VIEW = "NightPointView"; //number
export const MORNING_POINT_VIEW = "MorningPointView"; // number
export const RENDERING_MOVIE = "RenderingMovie"; //string

export const PROJECT_QUANTITY = "ProjectQuantity"; // number
export const RENDER_OPACITY = "RenderOpacity"; //string
export const RENDER_NO_OPACITY = "RenderNoOpacity"; //string
export const VIDEO_TYPE = "VideoType"; //string
export const FILM_TYPE = "FilmType"; //string
export const ADVERTISED_PRODUCT = "AdvertisedProduct"; //string
export const DESCRIPTION_PRODUCT = "DescriptionProduct"; //string
export const CHRONOMETRY_VIDEO = "Chronometry"; //string
export const BUDGET = "Budget"; //string
export const MATERIALS = "Materials"; //string
export const EXAMPLE_LINK = "ExampleLink"; //string
export const ANIMATION_TASK = "AnimationTask"; //string
export const SCENARIO = "Scenario"; //string
export const PROJECT_TASK = "ProjectTask"; //string
export const TECHNICAL_REQUIREMENTS = "TechnicalRequirements"; //string
export const MODEL_QUANTITY = "ModelQuantity";
